<div style="font-size: 1em; margin: 1em 0 1em 0; border: 1px solid #86989B; background-color: #f7f7f7; padding: 0;">
<span style='color:Black'>
<div class="alert alert-info">
<img align="left" src='imgs/imgnumlogo.svg'  width='10%'><img align="right" src='imgs/imgnumlogo.svg'  width='10%'>
    <h1 align="center">Numpy</h1> 
    <h3 align="center"> International Graduate School of Artificial Intelligence - YunTech </h3>
    <h5 align="center">  </h5>
</div>
</span>
</div>


#### Ref: https://numpy.org/doc/1.24/

# <span style='color:Black'>**NumPy Tutorial** (Array and Matrix)</span>

<img src='imgs/icon1.png'  width='1.2%'> NumPy is a Python library for working with arrays.

<img src='imgs/icon1.png'  width='1.2%'> NumPy is short for "Numerical Python".

<img src='imgs/icon1.png'  width='1.2%'> NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

<div style="font-size: 1em; margin: 1em 0 1em 0; border: 1px solid #86989B; background-color: #8fffff; padding: 0;">

#### <span style='color:Black'>**What is NumPy?**</span>

<div align="center">
<img src='imgs/imgnum.png'  width='40%'>
</div>

#### <img src='imgs/icon3.png'  width='1.2%'>  **How are Lists different from NumPy?**

<div align="center">
<img src='imgs/imgnumlist.png'  width='40%'>
</div>


#### <img src='imgs/icon3.png'  width='1.2%'>  **Why is NumPy faster? - Fixed type**
- Faster to read less bytes of memory

- No type checking when iterating through objects

</div>

**Installation NumPy**

Install it using this command:
``` command
C:\Users\Your Name>pip install numpy
```

**Import NumPy**

We use the following statement to import 'numpy' package:

``` Python
import numpy as np
```

Now the NumPy package can be referred to as np instead of numpy.

#### Creating arrays

<span style='color:DarkGreen'> **Example:**<br> NumPy Creating Arrays </span>

In [1]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


<div align="center">
<img src='imgs/imgnumshape1.png'  width='20%'>
</div>

#### Zeros, Ones and Empty Arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones(3)

array([1., 1., 1.])

In [5]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# Create an empty array with 3 elements

np.empty(3)

array([1., 1., 1.])

In [7]:
np.empty((2, 4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.05697205e-307],
       [2.67014974e-306, 1.42413555e-306, 1.78019082e-306,
        1.37959740e-306]])

<div style="font-size: 1em; margin: 1em 0 1em 0; border: 1px solid #86989B; background-color: #f7f7f7; padding: 0em 1em 1em 0.1em;">
<p style="margin: 0; padding: 0.1em 0 0.1em 0.5em; color: black; border-bottom: 1px solid #86989B; font-weight: bold; background-color: #28A745;">
Activity 1
</p>
<p style="margin: 0.5em 1em 0.5em 1em; padding: 0;">

Create a NumPy array of 5 integers from 0 to 4:

</p>
</div>



<div style="font-size: 1em; margin: 1em 0 1em 0; border: 1px solid #86989B; background-color: #f7f7f7; padding: 0em 1em 1em 0.1em;">
<p style="margin: 0; padding: 0.1em 0 0.1em 0.5em; color: black; border-bottom: 1px solid #86989B; font-weight: bold; background-color: #28A745;">
Activity 2
</p>
<p style="margin: 0.5em 1em 0.5em 1em; padding: 0;">

Create a 2D NumPy array of shape (4, 2) with all elements initialized to 0:

</p>
</div>



#### Random Numbers

In [8]:
#Generate a random integer from 0 to 100

np.random.randint(100)

30

In [9]:
# Generate 5 random integers from 0 to 100

np.random.randint(100, size = (5))

array([76, 83, 21, 32, 19])

In [10]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100

np.random.seed(4)

np.random.randint(100, size = (3, 5))

array([[46, 55, 69,  1, 87],
       [72, 50,  9, 58, 94],
       [55, 55, 57, 36, 50]])

#### Sum, max, min, mean

In [11]:
arr3 = np.array([[2, 1, 5], [0, 7, 3], [8, 6, 9]])

arr3

array([[2, 1, 5],
       [0, 7, 3],
       [8, 6, 9]])

In [12]:
arr3.sum()

41

In [13]:
arr3.sum(0)

array([10, 14, 17])

In [14]:
arr3.sum(1)

array([ 8, 10, 23])

In [15]:
arr3.max()

9

In [16]:
arr3.max(0)

array([8, 7, 9])

In [17]:
arr3.max(1)

array([5, 7, 9])

In [18]:
arr3.mean()

4.555555555555555

In [19]:
(arr3.sum())/(arr3.size)

4.555555555555555

#### Array indexing

<div align="center">
<img src='imgs/numpy_index.png'  width='40%'>
</div>

In [20]:
# Access Array Elements
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

print(arr[1])

print(arr[2] + arr[3])

1
2
7


In [21]:
# Access 2-D Arrays
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

2nd element on 1st row:  2
5th element on 2nd row:  10


In [22]:
# Access 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [23]:
# Negative Indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


#### Slicing arrays

<span style='color:DarkGreen'> **Example:**<br> Slice elements </span>

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

print(arr[4:])

print(arr[:4])

print(arr[-3:-1]) # Negative Slicing

print(arr[1:5:2]) # Return every other element from index 1 to index 5

print(arr[::2]) # Return every other element from the entire array

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


<div align="center">
<img src='imgs/numpy_indexing.png'  width='40%'>
</div>

In [25]:
# Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

print(arr[0:2, 1:4])

print(arr[1, 1:4])

[3 8]
[[2 3 4]
 [7 8 9]]
[7 8 9]


#### Array Shape

In [26]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [27]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [28]:
# Reshaping
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

newarr1 = arr.reshape(2, 3, 2)

print(newarr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [29]:
# Unknown Dimension
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(-1, 4, 1)

print(newarr)

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]]


In [30]:
# Convert the array into a 1D array
newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6 7 8]


<div style="font-size: 1em; margin: 1em 0 1em 0; border: 1px solid #86989B; background-color: #f7f7f7; padding: 0em 1em 1em 0.1em;">
<p style="margin: 0; padding: 0.1em 0 0.1em 0.5em; color: black; border-bottom: 1px solid #86989B; font-weight: bold; background-color: #28A745;">
Activity 3
</p>
<p style="margin: 0.5em 1em 0.5em 1em; padding: 0;">

Reshape a 1D NumPy array into a 2D NumPy array of shape (2, 3):

</p>
</div>



In [1]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6])

result = arr1.reshape((2, 3))
print(result)

[[1 2 3]
 [4 5 6]]


#### Joining Array

<div align="center">
<img src='imgs/numpy_concatenate.png'  width='8%'>
</div>

In [31]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [32]:
# Join two 2-D arrays along rows (axis=1)
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


#### Splitting Array

<div align="center">
<img src='imgs/numpy_split.png'  width='30%'>
</div>

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

newarr1 = np.array_split(arr, 4)

print(newarr1)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [34]:
# Split the 2-D array into three 2-D arrays
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


#### Searching Arrays

In [35]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
print(x)

x = np.where(arr % 2 == 0)
print(x)

x = np.where(arr % 2 == 1)
print(x)

(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)
(array([0, 2, 4], dtype=int64),)


#### Sorting Arrays

In [36]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [37]:
arr = np.array(['red', 'green', 'blue'])

print(np.sort(arr))

['blue' 'green' 'red']


#### Filtering Arrays

<div align="center">
<img src='imgs/numpy_filter.png'  width='30%'>
</div>

In [38]:
# Create an array from the elements on index 0 and 2.
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [39]:
# Create a filter array that will return only values higher than 42
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [40]:
# Creating Filter Directly From Array
# Create a filter array that will return only values higher than 42.
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


<div style="font-size: 1em; margin: 1em 1em 1em 1em; border: 1px solid #86989B; background-color: #8fffff;padding: 1em 1em 1em 1em; ">
<div align="center">
<img src='imgs/icon5.png'  width='10%'>

<h2 style="text-align: center;color: Darkgreen">Pandas</h2>


</div>